version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7-jammy

    container_name: resugenie-mongodb-container

    ports:
      - "27007:27017"
    
    volumes:
      - ./mongodb:/data/db
    
    networks:
      - backend
    
    restart: always

    


networks:
  backend: